name: Create Feature Branch, Add Folder, and Copy Code from Another Repo

on:
  workflow_dispatch:  # Trigger manually via GitHub UI

jobs:
  create-branch-and-copy-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository on MASTER branch
      uses: actions/checkout@v4
      with:
        ref: master  # Checkout the MASTER branch

    - name: Check the list of branches 
      run: |
        git branch -a

    - name: Create a new feature branch from MASTER
      run: |
        git branch feature-branch  

    - name: Checkout the branch from the other repository
      run: |
        git checkout feature-branch  

    - name: Create a folder in the feature branch
      run: |
        mkdir -p new-folder  
        echo "Folder created" 

    - name: Add another repository as a remote
      run: |
        git clone https://github.com/akshayvats7/Youtube-Data-Analysis.git 
        git fetch Youtube-Data-Analysis  

    - name: Copy code from the other repository to the new folder
      run: |
        cp -r * ../new-folder/  # Copy code from other repo's branch to the new folder in the feature branch
        # Optionally: exclude hidden files or specific files if needed

    - name: Add and commit changes
      run: |
        git add .  # Add all the new changes (including folder and copied code)
        git commit -m "Add new folder and copy code from another repo"  # Commit the changes

    - name: Push the feature branch
      run: |
        git push origin feature-branch  # Push the feature branch to the repository
